<template>
    <div class="image-container relative">
      <img :src="product.img" alt="Gambar" class="object-cover h-400 w-full">
    </div>
    <h1 class="text-left text-3xl font-bold text-black mt-2 pl-20 pt-10">Finibus Bonorul El Rumi</h1>
    <div class="flex items-center mt-2 pl-20">
      <h3 class="text-sm font-bold text-gray-800">Written By John Doe</h3>
      <h3 class="text-sm font-semibold text-gray-500 ml-4">Monday May 29</h3>
      <br>
    </div>
    <div class="text-justify font-normal text-black mt-2 pl-20 pt-10 pr-20 tracking-tight leading-snug">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
        </p>
    </div>
    <br>
    <div class="text-left font-normal text-black mt-2 pl-20 pt-5 pr-20 tracking-tight leading-snug">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
        </p>
    </div>

    <h3 class="text-sm font-bold text-gray-800 mt-4 pl-20 pt-10">Additional Information</h3>
    <div class="text-left font-normal text-black mt-2 pl-20 pt-5 pr-20 tracking-tight leading-snug">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
        </p>
    </div>

    <h2 class="text-xl font-bold text-gray-800 mt-4 pl-20 pt-10">Section</h2>

    <div class="text-left font-normal text-black mt-2 pl-20 pt-5 pr-20 tracking-tight leading-snug">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
        </p>
    </div>

    <h2 class="text-2xl font-bold text-gray-800 mt-4 pl-20 pt-10">Section 2.10</h2>

    <div class="text-left font-normal text-black mt-2 pl-20 pt-5 pr-20 tracking-tight leading-snug">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis, lectus quis efficitur sagittis, ante enim ultrices ex, eget hendrerit ipsum sapien vel ligula. In hac habitasse platea dictumst. Sed nec diam id justo aliquam commodo. Aliquam pretium urna sed lacus interdum, sed ultrices ipsum fermentum. Quisque euismod tempor libero, at consectetur odio aliquam nec. Nulla rutrum enim eget eros vehicula, nec bibendum turpis ullamcorper. Maecenas commodo risus ac est fermentum, a faucibus magna scelerisque. Sed ac sem ac ligula finibus accumsan a sed arcu. Sed sollicitudin nunc id semper sollicitudin.
        </p>
    </div>
    
    <button @click="scrollToTop" class="fixed bottom-10 right-10 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
        Scroll to Top
      </button>
  </template>
  
  <script>
  import { datas } from "@/data";
  
  export default {
    data() {
      return {
        product: {},
      };
    },
    mounted() {
      this.getProductById(1); // Menggunakan ID 1 secara langsung untuk halaman detail
    },
    methods: {
      getProductById(id) {
        this.product = datas.find(item => item.id === id);
      },
      scrollToTop() {
        window.scrollTo({
          top: 0,
          behavior: 'smooth'
        });
      },
    },
  };
  </script>
  
  <style>
  .image-container {
    height: 400px;
    max-width: 100vw;
    overflow: hidden;
  }
  /* Additional styles for the scroll to top button */
#scrollToTopButton {
    position: fixed;
    bottom: 10px;
    right: 10px;
  }
  </style>
  